### ISSUE TITLE
armbian hangs under heavy disk io.

### ISSUE THREAD

**Issue by ivahos** [HelmSecure/armbian-images#10] opened 2022-12-27 19:14 UTC
Hi, I have reflashed my V2A helm, and I have been able to reformat the internal nvdimm disk as well. However, the system seems to hang after some time with heavy disk io activity with an SMP exception. I have moved my email to a docker setup, and every time I try to copy the emails from my VM that has been running my email since I migrated it off the helm server. 

For me, it’s straightforward to recreate the problem. Run the following command:
dd if=/dev/zero of=/nvme_mountpoint/data.dd bs=1M count=8000

This command never completes for me. The helm just goes unresponsive after around 3GB written.

**Comment by dsigurds** [comment] 2022-12-28 05:40
Thanks for reporting.  I'll investigate and see if I can reproduce the issue.

**Comment by mongobit** [comment] 2022-12-28 07:41
mind if i ask where you got the instructions for that? i can see the 7gigs of emmc memory but not seeing my 1TB M.2 yet.

**Comment by ivahos** [comment] 2022-12-28 08:34
> mind if i ask where you got the instructions for that? i can see the 7gigs of emmc memory but not seeing my 1TB M.2 yet.

the nvme is /dev/nvme0n1. Just run fdisk —wipe always /dev/nvme0n1 to create a partition on it

**Comment by prescottk** [comment] 2022-12-28 18:49
I can totally reproduce the issue simply by following the same instructions in your email using dd.
This essentially makes the 1T disk unusable.

**Comment by dsigurds** [comment] 2022-12-28 18:58
> I can totally reproduce the issue simply by following the same instructions in your email using dd.
> 
> This essentially makes the 1T disk unusable.

Is your Helm a v2a as well?

**Comment by prescottk** [comment] 2022-12-28 19:00
Yes it is.

**Comment by rpooley** [comment] 2022-12-28 21:45
I too have experienced this issue when trying to clone the mmcblk2 to mmcblk1 using dd.
The system hangs and it needs to be rebooted, attempting a new ssh connection fails.

**Comment by l3nticular** [comment] 2022-12-28 21:55
Tangentially, you probably want an LVM volume on your NVM.  Helm software used one so you can just clear it out instead of using fdisk.

apt install lvm2
lvdisplay 
lvremove <volume name>
vgdisplay
vgremove <group name>
pvremove /dev/nvme0n1

then you can do pvcreate, vgcreate, lvcreate

**Comment by jimminycreeket** [comment] 2023-01-04 20:06
How did you get Docker functioning?

**Comment by gomsec** [comment] 2023-01-08 04:05
Are there any extra steps I need to do for armbian to see my 1TB drive?

**Comment by gomsec** [comment] 2023-01-09 22:29
> 
I ended up reseating the drive and now my system is able to see the drive.

**Comment by elyk53** [comment] 2023-01-29 22:44
I've got another instance of this issue, also Helm v2a, 512GB SSD. I've left shell windows open monitoring `journalctl -f` and `dmesg -w` and nothing stands out in the final log lines as being related in any way to the cause of the hang.

If there's any other troubleshooting that I can perform to help get to the bottom of this, let me know.

**Comment by kearneyk-up** [comment] 2023-01-30 06:01
In an effort to identify workarounds, I ran the `dd` experiment in two other data destinations:
1. A different SSD in an external case connected to the right hand (when looking at the device from the back) USB-C port (the drive did not enumerate at all when connected to the USB-C port closest to the Ethernet port). 
2. A network share hosted on another computer on my network.

Both triggered the same hang.

So this seems to indicate that the problem is related to the mere existence of a high I/O load, and not to anything specific to the internal SSD.

**Comment by elyk53** [comment] 2023-01-30 06:06
In an attempt to identify workarounds, I ran the `dd` experiment with two additional targets:
1. A different SSD in an external case, connected to the right-most (when looking at the device from the back) USB-C port (the drive did not enumerate when plugged in to the USB-C port closest to the ethernet port).
2. A network share hosted on a different computer.

Both triggered the same hanging behavior.

This seems to indicate that the problem is related to the existence of high I/O load in any form, rather than being linked to something about the particular interface used by the internal SSD.

**Comment by ivahos** [comment] 2023-01-31 10:41
> This seems to indicate that the problem is related to the existence of high I/O load in any form, rather than being linked to something about the particular interface used by the internal SSD.

I am suspecting that this is the root cause of the strange hangs we had while helm vas solvent and running their own image. Whenever the machine did something like indexing a large folder or something else that generated large amounts of IO it had a chance to hang.

With the staff having gone missing, this leaves our helms in a bad place. The way it is now its only useful as a machine you can run cpu intensive tasks that do little io..

**Comment by l3nticular** [comment] 2023-01-31 13:47
Agreed.  One thought floating through my head is if there is a FUSE file system that can virtualize and artificially slow down I/O operations.

**Comment by dsigurds** [comment] 2023-02-04 04:00
The original Helm OS created an LVM volume on the SSD and then overlayed that with dm-crypt to create an encrypted volume.  We configured it as an LVM volume because we anticipated expanding the /data partition with external drives connected over USB.  This definitely slowed down I/O.  However, I've gone back to our original OS and removed those multiple layers of indirection to see if I can reproduce the crash and am unable to.  This means most likely that there is an issue with the Armbian kernel build.  The source used for the kernel for the original Helm OS is divergent from the source used by Armbian Rockchip devices.  It will likely be difficult to track down but I'm working on it.  Sorry for the issue.

**Comment by l3nticular** [comment] 2023-02-07 21:22
@kkanatcit you will probably hit the hang at some point. Just be ready to power cycle it.

@dsigurds it also hangs with a dm-crypt volume on LVM.  So it seems likely to be related to the armbian image in general since it also fails on a network share.

**Comment by l3nticular** [comment] 2023-02-07 21:23
(LVM instructions are here, btw:
https://reddit.com/r/HelmServerMods/comments/10pfcdf/setting_up_ssd/)

I didn’t have any issues setting up LVM or formatting, purely when doing huge data copies like that.

**Comment by l3nticular** [comment] 2023-02-07 21:25
It’s interesting that it always fails around 3GB when the free ram on a base install is also about 3GB.  Perhaps the file system caching is not able to keep up and exhausts the ram?

**Comment by l3nticular** [comment] 2023-02-07 22:51
It’s definitely related to the file system cache.  Adding flag to dd to bypass the cache works:

``` 
root@helm:~# dd if=/dev/zero of=/mnt/test/data4.dd bs=1M count=8000 oflag=direct
8000+0 records in
8000+0 records out
8388608000 bytes (8.4 GB, 7.8 GiB) copied, 23.5282 s, 357 MB/s
```

**Comment by l3nticular** [comment] 2023-02-08 00:42
Setting the file system mount as “sync” does *not* fix the problem. The cache still grows during the copy without the direct flag. 
Bad:
![6A25EB1A-C5A2-48DB-8ECC-9B6CB9AFD532](https://user-images.githubusercontent.com/11479790/217399498-d89a9cef-f1b4-4469-a4e0-9bad5f0efe2a.jpeg)

good:
![ABE661C5-AA03-4531-972F-26CEBE46DEFA](https://user-images.githubusercontent.com/11479790/217399524-b0c74239-dc93-4dd5-98a3-8753b069b6ed.jpeg)

**Comment by dsigurds** [comment] 2023-02-09 17:41
The issue corresponds to the version of u-boot used.  I'll be releasing a new build with a fix relatively soon.  Thanks for all the reporting on it and work in trying to diagnose the issue.

**Comment by dsigurds** [comment] 2023-02-21 03:22
This issue has been resolved with this image: https://github.com/HelmSecure/armbian-images/releases/download/v22.11.2-build-48/Armbian_22.11.2-build-48_Helm-v2a_bullseye_legacy_4.4.213_minimal.img

Unfortunately, the package update doesn't work to update u-boot and so a full image reflash is required to get the fix.  Make sure to backup any data so you can restore after the reflash.

**Closed by dsigurds** 2023-02-21 03:22 UTC

**Comment by krioso** [comment] 2023-02-21 08:36
Is there a reason why the 4.4 kernel is being used? Is there or will there be a way to use a newer kernel? The 4.4. kernel is past end of life.

**Comment by elyk53** [comment] 2023-02-25 18:15
Reflashed and confirmed that this fixes the disk issues. Thanks for the fix!
